---
name: Build and Publish PDF

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv-hhuang.tex

      # - name: Publish PDF
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_KEY }}
      #     passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
      #     source: cv-hhuang.pdf
      #     target: ~/public_html/share
      #     use_insecure_cipher: true

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add cv-hhuang.pdf
          git commit -a -m "export PDF CV"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
