---
name: Build and Publish PDF

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Build PDF
        uses: xu-cheng/latex-action@v4
        with:
          root_file: cv-hhuang.tex